version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: travel-planner-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
    networks:
      - travel-planner-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3000/api}
        - VITE_AMAP_KEY=${VITE_AMAP_KEY}
    container_name: travel-planner-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - travel-planner-network

networks:
  travel-planner-network:
    driver: bridge

